### ISSUE TITLE
FAQ Page and Profile page Creation

### ISSUE THREAD

**Issue by Khemini** [zuri-training/excel_comp_team_106#10]

**Comment by Khemini** [comment]
Complete

**Comment by Dhayvhiid** [comment]
Design and interaction for both mobile and Desktop done.

**Comment by Khemini** [comment]
For desktop
https://www.figma.com/file/rxBh6oIKJ0Hb96TlXKoF7f/Team-106_ExcelComp---TEAM-DESIGN-LIBRARY?node-id=1418%3A3794

**Comment by Khemini** [comment]
For mobile

https://www.figma.com/file/rxBh6oIKJ0Hb96TlXKoF7f/Team-106_ExcelComp---TEAM-DESIGN-LIBRARY?node-id=1418%3A4184
