### ISSUE TITLE
Landing page for unauthenticated users (Desktop)

### ISSUE THREAD

**Issue by Khemini** [zuri-training/excel_comp_team_106#25]
Contains the following sections

Hero section with Pri. CTA
What we offer
How it works
Advanced features
Why we stand out
A second section with Pri. CTA

**Comment by New-Marvee** [comment]
I resolved this issue by designing everything assingned to me:

Hero section with Pri. CTA
What we offer
How it works
Advanced features
Why we stand out
A second section with Pri. CTA


Here's a pictorial representation attach
![Unauthenticated Landing page by Marvy (resized)](https://user-images.githubusercontent.com/110172813/183963368-22d1b664-e982-4417-aa1c-3a804c0e913f.png)
ed below...
