### ISSUE TITLE
Mobile screens prototype update

### ISSUE THREAD

**Issue by Ola2nji** [zuri-training/excel_comp_team_106#6]
100% done

**Comment by Dhayvhiid** [comment]
Guess we can say 99% done now.

**Comment by Khemini** [comment]
Kindly cross check the prototype on the old design file. It seems the forgot password prototype didn't flow well

**Comment by Ola2nji** [comment]
After re setting the password a user can't go back

**Comment by Dhayvhiid** [comment]
Done. [View](https://www.figma.com/proto/rxBh6oIKJ0Hb96TlXKoF7f/Team-106_ExcelComp---TEAM-DESIGN-LIBRARY?node-id=1471%3A2228&scaling=scale-down&page-id=512%3A2&starting-point-node-id=1471%3A2228&show-proto-sidebar=1) <br>
