### ISSUE TITLE
Animation Pages for Upload Pages (for mobile and desktop)

### ISSUE THREAD

**Issue by Owolade1** [zuri-training/excel_comp_team_106#7]
How far about the animations in the upload screen

**Comment by Holumidey** [comment]
I think it is done

**Comment by Khemini** [comment]
https://www.figma.com/file/rxBh6oIKJ0Hb96TlXKoF7f/Team-106_ExcelComp---TEAM-DESIGN-LIBRARY?node-id=1184%3A2035
